//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export namespace Enums {
	export enum UserRole {
		User = 1,
		Admin = 2
	}
}
export namespace JsonModels.Common {
	export interface PagedRequest
	{
		page: number;
		pageSize: number;
		search?: string;
	}
	export interface PagedResponse<T>
	{
		items: T[];
		totalCount: number;
		page: number;
		pageSize: number;
	}
}
export namespace JsonModels.Auth {
	export interface AuthResponse
	{
		user: JsonModels.Auth.UserModel;
		tokenExpiresAtUtc: string;
		refreshTokenExpiresAtUtc: string;
	}
	export interface LoginRequest
	{
		email: string;
		password: string;
	}
	export interface RegisterRequest
	{
		email: string;
		password: string;
		firstName: string;
		lastName: string;
	}
	export interface UpdateProfileRequest
	{
		firstName: string;
		lastName: string;
	}
	export interface UserModel
	{
		id: number;
		email: string;
		firstName?: string;
		lastName?: string;
		roles: Enums.UserRole[];
	}
}
export interface JsonData<T>
{
	success: boolean;
	error?: string;
	data?: T;
}
