export * from "./JsonModels";

import type { JsonModels } from "./backend";

export type AccountOperationResult = JsonModels.Bank.MoneyOperations.AccountOperationResultModel;
export type ApiError = JsonModels.Diagnostics.ApiErrorModel;
export type BankAccount = JsonModels.Bank.Accounts.BankAccountModel;
export type BankAccountDetails = JsonModels.Bank.Accounts.BankAccountDetailsModel;
export type CompanyRepresentative = JsonModels.Bank.Customers.CompanyRepresentativeModel;
export type Credit = JsonModels.Bank.Credits.CreditModel;
export type CreditDetails = JsonModels.Bank.Credits.CreditDetailsModel;
export type CreditInstallmentPaymentResult = JsonModels.Bank.MoneyOperations.CreditInstallmentPaymentResultModel;
export type CreditPayment = JsonModels.Bank.Credits.CreditPaymentModel;
export type CreditPaymentResult = JsonModels.Bank.Credits.CreditPaymentResultModel;
export type CreditPricingChange = JsonModels.Bank.Credits.CreditPricingChangeModel;
export type CreditTerms = JsonModels.Bank.Credits.CreditTermsModel;
export type CreditTermsFee = JsonModels.Bank.Credits.CreditTermsFeeModel;
export type CreditTypeCondition = JsonModels.Bank.CreditConditions.CreditTypeConditionModel;
export type Customer = JsonModels.Bank.Customers.CustomerModel;
export type CustomerAccountSummary = JsonModels.Bank.Customers.CustomerAccountSummaryModel;
export type CustomerCreditSummary = JsonModels.Bank.Customers.CustomerCreditSummaryModel;
export type CustomerDetails = JsonModels.Bank.Customers.CustomerDetailsModel;
export type CustomerEdit = JsonModels.Bank.Customers.CustomerEditModel;
export type CustomerLookup = JsonModels.Bank.Customers.CustomerLookupModel;
export type DepositRequest = JsonModels.Bank.MoneyOperations.DepositRequestModel;
export type DepositRequestQueue = JsonModels.Bank.MoneyOperations.DepositRequestQueueModel;
export type MoneyTransaction = JsonModels.Bank.MoneyOperations.MoneyTransactionModel;
export type PublicCreditCondition = JsonModels.Bank.CreditConditions.PublicCreditConditionModel;
export type SavedCalculation = JsonModels.Calculators.SavedCalculationModel;
export type SavedCalculationDetails = JsonModels.Calculators.SavedCalculationDetailsModel;
export type StaffUserGrid = JsonModels.Auth.StaffUserGridModel;
export type StaffUserPage = JsonModels.Auth.StaffUserPageModel;
export type StaffUserSummary = JsonModels.Auth.StaffUserSummaryModel;
export type User = JsonModels.Auth.UserModel;
export type UserAccess = JsonModels.Auth.UserAccessModel;
export type UserAccessPage = JsonModels.Auth.UserAccessPageModel;
export type UserAccessSummary = JsonModels.Auth.UserAccessSummaryModel;
